### ISSUE TITLE
Model form Blender test

### ISSUE THREAD

**Issue by gitsunekei1445** [gitsunekei1445/8Engine#14]
- Render tpye .Object
- file model on google Drive shang on issues here

**Comment by yuttanasuphap** [comment]
[https://drive.google.com/file/d/1XLaERphthyBDgmpwiAaokdsLXEqU6SL-/view](url)
ลิ้งเกี่ยวกับคู่มือการสร้างโมเดลด้วย blender

[https://download.blender.org/documentation/BlenderHotkeyReference.pdf](url)
ลิ้งค์เกี่ยวกับคีร์ลัดของโปรแกรม blender
